name: maze_l2rpn_icaps_2021
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.7
  - pytorch==1.8.1 py3.7_cpu_0
  - pygraphviz==1.3
  - pip==21.1.1
  - pip:
    - numba==0.53.1
    - grid2op==1.6.0.post1
    - maze-rl==0.1.8
    - -e .